# Generated by Django 5.0.6 on 2024-06-02 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='ocupation',
            new_name='occupation',
        ),
    ]
